### ISSUE TITLE
Add ignore pattern for each log level

### ISSUE THREAD

**Issue by Primajin** [Primajin/webapp-console-log-action#12]
As a user of the webapp-console-log-action I want to be able to add ignore patterns for every log level, so that I can ignore common or known errors, warnings etc that I expect to happen.

For example: I expect some images in my test app to return a 404 but this will not happen in production.

```yaml
      - name: Use WebApp Console Log Action
        uses: Primajin/webapp-console-log-action@v1
        with:
          webapp-url: http://localhost
          regexp-error: "Failed[\D]+404 \(\)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This will filter out all errors that throw

```
Failed to load resource: the server responded with a status of 404 ()
```

There should be filters for every log level like so:
```
regexp-verbose
regexp-info
regexp-warning
regexp-error
```
